// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYWMTrNW9giJ24TUI6ik6q1kLqLVawAzM',
    appId: '1:10325572935:web:4e160533c0536d41d5a062',
    messagingSenderId: '10325572935',
    projectId: 'mobile-8ff04',
    authDomain: 'mobile-8ff04.firebaseapp.com',
    storageBucket: 'mobile-8ff04.firebasestorage.app',
    measurementId: 'G-45WFWNWX0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf-AXEtPpDy18wk7R7nVkaorWzv8kLJQ0',
    appId: '1:10325572935:android:8d1955ed56615d8dd5a062',
    messagingSenderId: '10325572935',
    projectId: 'mobile-8ff04',
    storageBucket: 'mobile-8ff04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD57m4j2HEeKhQdhZFXJeVCqFwIDuui_1U',
    appId: '1:10325572935:ios:97d5e01d3444d6a6d5a062',
    messagingSenderId: '10325572935',
    projectId: 'mobile-8ff04',
    storageBucket: 'mobile-8ff04.firebasestorage.app',
    iosBundleId: 'com.example.appMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD57m4j2HEeKhQdhZFXJeVCqFwIDuui_1U',
    appId: '1:10325572935:ios:97d5e01d3444d6a6d5a062',
    messagingSenderId: '10325572935',
    projectId: 'mobile-8ff04',
    storageBucket: 'mobile-8ff04.firebasestorage.app',
    iosBundleId: 'com.example.appMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYWMTrNW9giJ24TUI6ik6q1kLqLVawAzM',
    appId: '1:10325572935:web:71f77b6dd65d2806d5a062',
    messagingSenderId: '10325572935',
    projectId: 'mobile-8ff04',
    authDomain: 'mobile-8ff04.firebaseapp.com',
    storageBucket: 'mobile-8ff04.firebasestorage.app',
    measurementId: 'G-N6NEJ1RZ9H',
  );

}